# Generated by Django 4.2.7 on 2023-12-24 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0003_studentgroup"),
    ]

    operations = [
        migrations.AddField(
            model_name="teachers",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="teachers",
                to="school.groups",
            ),
        ),
    ]
