# Generated by Django 4.2.7 on 2023-12-24 23:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0004_teachers_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="students",
            name="phone",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
